/raid/home/automathon_2024/account6/.local/lib/python3.10/site-packages/torch/cuda/__init__.py:118: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
  1%|▊                                                                                                                                         | 9/1499 [00:01<03:42,  6.70it/s]
Training model:
==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
DeepfakeDetector                         [2, 1]                    --
├─Flatten: 1-1                           [2, 1966080]              --
├─Linear: 1-2                            [2, 1]                    1,966,081
├─Sigmoid: 1-3                           [2, 1]                    --
==========================================================================================
Total params: 1,966,081
Trainable params: 1,966,081
Non-trainable params: 0
Total mult-adds (M): 3.93
==========================================================================================
Input size (MB): 15.73
Forward/backward pass size (MB): 0.00
Params size (MB): 7.86
Estimated Total Size (MB): 23.59
==========================================================================================
Training...




















 13%|██████████████████▏                                                                                                                     | 201/1499 [00:43<04:40,  4.64it/s]
Traceback (most recent call last):
  File "/raid/home/automathon_2024/account6/automathon-2024/run.py", line 278, in <module>
    for sample in tqdm(loader):
  File "/raid/home/automathon_2024/account6/.local/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/raid/home/automathon_2024/account6/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/raid/home/automathon_2024/account6/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/raid/home/automathon_2024/account6/.local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/raid/home/automathon_2024/account6/.local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
KeyboardInterrupt